global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "rebalancer"
    static_configs:
      - targets: ["host.docker.internal:9090"]
        labels:
          asset: "usdc"
      # Add more instances:
      # - targets: ["host.docker.internal:9091"]
      #   labels:
      #     asset: "usdt"
